version: '3.0'
services:
  notification-service:
    build: 
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    image: demo/notification-service:0.0.1-SNAPSHOT
    environment:
    - TOMCAT_MAX_CONNECTIONS=200
    - TOMCAT_MAX_THREADS=400
    - TOMCAT_BACKLOG=1
    - APP_OPTS=
    ports:
    - 11100:8080
    - 11100:6000
    networks:
    - dev-docker
networks:
  dev-docker: null
